create table if not exists public.roulette_history (
    id bigint generated by default as identity primary key,
    number smallint not null check (number >= 0 and number <= 36),
    timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);
